services:
  - type: web
    name: bp-app
    runtime: node
    region: frankfurt
    repo: https://github.com/ArchOrn/esgi_render_bp_4al2
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bp-db
          property: connectionString

databases:
  - name: bp-db
    region: frankfurt
    plan: free
